<Project Sdk="Microsoft.NET.Sdk.Razor">

	<PropertyGroup>
		<TargetFrameworks>net9.0;net10.0;net11.0</TargetFrameworks>
		<TestTfmsInParallel>true</TestTfmsInParallel>
		<NoWarn>$(NoWarn);CS0618</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="AutoFixture" />
		<PackageReference Include="AwesomeAssertions" />
		<PackageReference Include="AwesomeAssertions.Analyzers">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="bunit" />
		<PackageReference Include="NSubstitute" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\NTComponents.Analyzers\NTComponents.Analyzers.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
		<ProjectReference Include="..\..\NTComponents\NTComponents.csproj" />
		<ProjectReference Include="..\..\NTComponents.AspNetCore\NTComponents.AspNetCore.csproj" />
		<ProjectReference Include="..\..\NTComponents.Extensions\NTComponents.Extensions.csproj" />
		<ProjectReference Include="..\..\Submodules\NTComponents.Charts\NTComponents.Charts\NTComponents.Charts.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Using Include="Bunit" />
		<Using Include="Xunit" />
		<Using Include="AwesomeAssertions" />
	</ItemGroup>
</Project>
