<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="..\PackageMetadata.props" />

    <PropertyGroup>
		<TargetFrameworks>net9.0;net10.0;net11.0</TargetFrameworks>
		<ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <PackageTags>Blazor;Components;.NET9;.NET10;.NET11</PackageTags>

    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\NTComponents\NTComponents.csproj" />
    </ItemGroup>

</Project>
